## Imbalanced Dataset Handling
1.Up Sampling
2.Down Sampling

In [1]:
import numpy as np
import pandas as pd

In [3]:
# Set the random seed for reproduciblity
np.random.seed(123)

#create a datframe with two classes
n_samples = 1000
class_0_ratio = 0.9
n_class_0 = int(n_samples*class_0_ratio)
n_class_1 = n_samples - n_class_0

In [4]:
n_class_0,n_class_1

(900, 100)

In [5]:
class_0 = pd.DataFrame({
    'feature_1': np.random.normal(loc =0,scale =1,size =n_class_0),
    'feature_2': np.random.normal(loc =0,scale =1,size =n_class_0),
    'target':[0]*n_class_0
})
class_1 = pd.DataFrame({
    'feature_1': np.random.normal(loc =2,scale =1,size =n_class_1),
    'feature_2': np.random.normal(loc =2,scale =1,size =n_class_1),
    'target':[1]*n_class_1 
})

In [7]:
df =pd.concat([class_0,class_1]).reset_index(drop = True)

In [8]:
df.head()

   feature_1  feature_2  target
0  -1.085631   0.551302       0
1   0.997345   0.419589       0
2   0.282978   1.815652       0
3  -1.506295  -0.252750       0
4  -0.578600  -0.292004       0

In [9]:
df['target'].value_counts()

target
0    900
1    100
Name: count, dtype: int64

## Up Sampling

In [14]:
df_minority = df[df['target'] == 1]
df_majority = df[df['target'] == 0]

In [15]:
df_minority.head()

     feature_1  feature_2  target
900   1.699768   2.139033       1
901   1.367739   2.025577       1
902   1.795683   1.803557       1
903   2.213696   3.312255       1
904   3.033878   3.187417       1

In [16]:
df_majority.head()

   feature_1  feature_2  target
0  -1.085631   0.551302       0
1   0.997345   0.419589       0
2   0.282978   1.815652       0
3  -1.506295  -0.252750       0
4  -0.578600  -0.292004       0

In [17]:
##Upsampling perform
from sklearn.utils import resample

In [19]:
df_minority_upsample = resample(df_minority,
                               replace = True, ## Sample With replacement
                                n_samples = len(df_majority),# to match the majority class)
                                random_state = 42
                               )

In [20]:
df_minority_upsample.shape

(900, 3)

In [24]:
df_minority_upsample.head()

     feature_1  feature_2  target
951   1.125854   1.843917       1
992   2.196570   1.397425       1
914   1.932170   2.998053       1
971   2.272825   3.034197       1
960   2.870056   1.550485       1

In [25]:
df_minority_upsample['target'].value_counts()

target
1    900
Name: count, dtype: int64

In [26]:
df_upsampled = pd.concat([df_majority,df_minority_upsample])

In [27]:
df_upsampled['target'].value_counts()

target
0    900
1    900
Name: count, dtype: int64

In [28]:
df_upsampled.head()

   feature_1  feature_2  target
0  -1.085631   0.551302       0
1   0.997345   0.419589       0
2   0.282978   1.815652       0
3  -1.506295  -0.252750       0
4  -0.578600  -0.292004       0

In [29]:
df_upsampled.tail()

     feature_1  feature_2  target
952   1.188902   2.189189       1
965   3.919526   1.980541       1
976   2.810326   3.604614       1
942   3.621531   2.168229       1
974   1.160887   2.489203       1

## Down Sampling

In [30]:
class_0 = pd.DataFrame({
    'feature_1': np.random.normal(loc =0,scale =1,size =n_class_0),
    'feature_2': np.random.normal(loc =0,scale =1,size =n_class_0),
    'target':[0]*n_class_0
})
class_1 = pd.DataFrame({
    'feature_1': np.random.normal(loc =2,scale =1,size =n_class_1),
    'feature_2': np.random.normal(loc =2,scale =1,size =n_class_1),
    'target':[1]*n_class_1 
})

In [31]:
df =pd.concat([class_0,class_1]).reset_index(drop = True)

In [32]:
df_minority = df[df['target'] == 1]
df_majority = df[df['target'] == 0]

In [34]:
df_majority_downsample = resample(df_majority,
                               replace = False, ## Sample Without replacement
                                n_samples = len(df_minority),# to match the minority class)
                                random_state = 42
                               )

In [35]:
df_majority_downsample.shape

(100, 3)

In [37]:
pd.concat([df_minority,df_majority_downsample])

     feature_1  feature_2  target
900  -0.643425   2.571923       1
901   1.551009   1.782767       1
902   1.641093   2.054318       1
903   2.133194   2.155998       1
904   1.355758   2.467810       1
..         ...        ...     ...
398   1.013666   0.083496       0
76    0.164480  -1.808980       0
196  -1.576624   0.525893       0
631  -0.540147   0.610282       0
751  -0.168798  -0.831334       0

[200 rows x 3 columns]

In [39]:
pd.concat([df_minority,df_majority_downsample]).value_counts()

feature_1  feature_2  target
-1.969990   0.130563  0         1
 1.866832   2.723282  1         1
 1.621476   1.877267  1         1
 1.628261   1.612792  1         1
 1.641093   2.054318  1         1
                               ..
 0.473474  -0.321933  0         1
 0.497556   1.095855  0         1
 0.519477   1.300336  0         1
 0.528702   1.508257  0         1
 4.799524   3.592020  1         1
Name: count, Length: 200, dtype: int64