## Nominal One Hot

In [1]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [4]:
# create a simple dataframe with a categorical variable
df = pd.DataFrame({
    'color' : ['red','blue','green','green','red','blue']
})

In [5]:
df

   color
0    red
1   blue
2  green
3  green
4    red
5   blue

In [7]:
## create an instance of one hot encoder
encoder = OneHotEncoder()

In [8]:
encoder.fit_transform(df[['color']])

<6x3 sparse matrix of type '<class 'numpy.float64'>'
	with 6 stored elements in Compressed Sparse Row format>

In [9]:
encoder.fit_transform(df[['color']]).toarray()

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [11]:
#fit the encoder to the dataframe and transform the categorical variable
encoded = encoder.fit_transform(df[['color']])

In [17]:
import pandas as pd
encoded_Df = pd.DataFrame(encoded.toarray(),columns = encoder.get_feature_names_out)

TypeError: Index(...) must be called with a collection of some kind, <bound method OneHotEncoder.get_feature_names_out of OneHotEncoder()> was passed

In [18]:
import seaborn as sns

In [19]:
sns.load_dataset('tips')

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [ ]:
pd.concat